### ISSUE TITLE
Audio Slider settings not being saved.

### ISSUE THREAD

**Issue by Neon-Oyun** [Fragjacker/DoW-Mod-Manager#27]
Hi!

Neon from Unification Discord here.

The mod manager (2.16) does not save audio volume settings, nor the “random sound” setting either. 

The audio volumes can be set ingame using the game's own sliders and the game will remember it. But it will not be reflected when looking in the mod manager. And on seemingly random occasions the mod manager’s (default) volume settings will override the game’s settings.

Launching as admin does nothing. There are no lines for audio settings in the modmanager.ini or the local.ini, but that could be by design.

EDIT: 3 confirmed cases (including me), I think there has been one or two further back reported in Unification tech-support.

**Comment by Fragjacker** [comment]
I may tag @IgorTheLight for this is well, since the settings window is his baby. We'll look into fixing this.

**Comment by Fragjacker** [comment]
Alright @Neon-Oyun this issue should be fixed as of commit b6fcfd27bcca8dbef83acb7088958906e43d00d2 published just now.

**Comment by Neon-Oyun** [comment]
Wow that was fast! Tested it and it seems to be working as intended now :)

**Comment by IgorTheLight** [comment]
I didn't even had time to react :-)
I will test those changes too!
Disclaimer: I didn't even touched the new code at all - all credit goes to Fragjacker :-)
