### ISSUE TITLE
Translations

### ISSUE THREAD

**Issue by Blueberryy** [Fragjacker/DoW-Mod-Manager#35]
DoW mod manager is great a software

**Comment by Fragjacker** [comment]
Thanks @Blueberryy! Though this place is reserved for issues/ideas/requests. If this post was intended to be issues/ideas/requests then make sure to rephrase this post and precisely state what you would like to be added.

**Comment by Blueberryy** [comment]
> Thanks @Blueberryy! Though this place is reserved for issues/ideas/requests. If this post was intended to be issues/ideas/requests then make sure to rephrase this post and precisely state what you would like to be added.

I mean will dow mod manager support translations/localizations from community for UI text?

**Comment by Fragjacker** [comment]
Maybe some day 😁

**Comment by Blueberryy** [comment]
Thanks for implementing that. Cheers!

**Comment by Fragjacker** [comment]
Ticket was closed due to inactivity, nothing was implemented. It may be reopened in the future if there is actually something to implement, if any.

**Comment by Blueberryy** [comment]
Buttons and other imprortant stuff should be enough to be translated.
